apiVersion: v1
kind: Service
metadata:
  name: dca-backend-loadbalancer
spec:
  selector:
    app: dca-backend-pod
  ports:
  - name: dca-loadbalancer-port
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
